"use client";
import {useEffect,useState} from "react";
import {supabase} from "../../lib";
import {useRouter} from "next/navigation";
import Shell from "../components/Shell";
const PL=["Spotify","Apple Music"];
export default function Profiles(){
 const [uid,setUid]=useState(""),[rows,setRows]=useState([]),[msg,setMsg]=useState(""),router=useRouter();
 useEffect(()=>{(async()=>{const {data:{user}}=await supabase.auth.getUser();if(!user)return router.push("/login");setUid(user.id);const {data}=await supabase.from("artist_profiles").select("*").eq("artist_id",user.id);setRows(PL.map(x=>data?.find(y=>y.platform===x)||{platform:x,has_profile:false,profile_url:"",profile_id:"",status:"not connected"}))})()},[router]);
 function edit(i,k,v){setRows(a=>a.map((x,j)=>j===i?{...x,[k]:v}:x))}
 async function save(i){const x=rows[i];if(x.profile_url&&!/^https?:\/\//i.test(x.profile_url))return setMsg(`${x.platform}: please paste the full official URL starting with https://`);const {error}=await supabase.from("artist_profiles").upsert({artist_id:uid,platform:x.platform,profile_url:x.profile_url||null,profile_id:x.profile_id||null,has_profile:!!x.profile_url,status:x.profile_url?"connected":"not connected",updated_at:new Date().toISOString()},{onConflict:"artist_id,platform"});setMsg(error?error.message:`${x.platform} profile saved.`)}
 async function request(i){const x=rows[i];const {error}=await supabase.from("artist_profiles").upsert({artist_id:uid,platform:x.platform,has_profile:false,status:"requested",updated_at:new Date().toISOString()},{onConflict:"artist_id,platform"});if(!error){const {data:ex}=await supabase.from("profile_requests").select("id").eq("artist_id",uid).eq("platform",x.platform).in("status",["requested","processing"]).limit(1);if(!ex?.length)await supabase.from("profile_requests").insert({artist_id:uid,platform:x.platform})}setMsg(error?error.message:`${x.platform} profile request sent to YOUNG BOYZ.`)}
 return <Shell><div className="page page-narrow"><header className="page-head"><div><p className="eyebrow">Artist settings</p><h1>Platform profiles</h1><p className="lead">Add your official Spotify and Apple Music artist pages. These links will be available when you submit releases.</p></div></header><div className="profile-notice">Have an existing artist profile? Paste the <b>official artist page URL</b> and, if available, the profile/artist ID. If you don't have one, click <b>We don't have a profile</b> and YOUNG BOYZ will handle the profile request/creation.</div><section className="profile-panel">{rows.map((x,i)=><div className="profile-row" key={x.platform}><div className="platform-name"><div className="platform-dot">{x.platform.slice(0,1)}</div><div><b>{x.platform}</b><span className={x.status==="connected"?"ok":x.status==="requested"?"wait":""}>{x.status==="connected"?"Connected":x.status==="requested"?"Profile requested":"No profile linked"}</span></div></div><div className="profile-actions"><input placeholder={`https://${x.platform.toLowerCase().replaceAll(" ","")}.com/artist/...`} value={x.profile_url||""} onChange={e=>edit(i,"profile_url",e.target.value)}/><input className="profile-id" placeholder="Artist / Profile ID (optional)" value={x.profile_id||""} onChange={e=>edit(i,"profile_id",e.target.value)}/><button className="profile-save" onClick={()=>save(i)}>Save profile</button><button className="profile-request" onClick={()=>request(i)}>We don't have a profile</button></div></div>)}{msg&&<div className="profile-message">{msg}</div>}</section></div></Shell>
}
